Repository CADELmx/GPD_BACKEND, pull requests merged in 2024-07, with the labels that each got.

#11 Created exception filter
  package-lock.json
  src/common/filters/custom-exception.filter.ts
  src/common/validation/custom-validation.pipe.ts
  src/main.ts
Labels: upgrade

#18 Subjects module added
  src/app.module.ts
  src/common/validation/custom-validation.pipe.ts
  src/educational-programs/educational-programs.controller.ts
  src/models/subject/create-subject.dto.ts
  src/models/subject/update-subject.dto.ts
  src/partial-templates/partial-templates.service.ts
  src/subject/subject.controller.spec.ts
  src/subject/subject.controller.ts
  src/subject/subject.module.ts
  src/subject/subject.service.spec.ts
  src/subject/subject.service.ts
Labels: enhancement

#20 Implementation of restrictions, validations and custom messages
  src/models/template/create-template.dto.ts
  src/models/template/update-template.dto.ts
  src/templates/templates.service.ts
Labels: upgrade

#26 CRUD Implementation for Areas with DTO and JSDoc Documentation
  src/app.module.ts
  src/areas/areas.controller.spec.ts
  src/areas/areas.controller.ts
  src/areas/areas.module.ts
  src/areas/areas.service.spec.ts
  src/areas/areas.service.ts
  src/models/area/create-area.dto.ts
  src/models/area/update-area.dto.ts
Labels: enhancement

#25 Hot Fix: inconsistency of changes since last merge conflicts resolution
  src/common/validation/custom-validation.pipe.ts
  src/educational-programs/educational-programs.controller.ts
  src/subject/subject.controller.ts
  src/subject/subject.service.ts
Labels: minor bug

#29 Added new CRUD endpoints and global features
  migration.sql
  package-lock.json
  prisma/migrations/20240710055915_/migration.sql
  prisma/migrations/20240710060023_/migration.sql
  prisma/migrations/20240712192549_update_personal_data/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/areas/areas.controller.spec.ts
  src/areas/areas.controller.ts
  src/areas/areas.module.ts
  src/areas/areas.service.spec.ts
  src/areas/areas.service.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/constants.ts
  src/auth/strategies/guards/jwt-auth.guard.ts
  src/auth/strategies/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/common/filters/custom-exception.filter.ts
  src/common/validation/custom-validation.pipe.ts
  src/educational-programs/educational-programs.controller.spec.ts
  src/educational-programs/educational-programs.controller.ts
  src/educational-programs/educational-programs.service.spec.ts
  src/educational-programs/educational-programs.service.ts
  src/interceptors/bigint.interceptor.ts
  src/main.ts
  src/models/EducationalPrograms/create-educational-program.dto.ts
  src/models/EducationalPrograms/update-educational-program.dto.ts
  src/models/area/create-area.dto.ts
  src/models/area/update-area.dto.ts
  src/models/partialTemplate/create-partial-template.dto.ts
  src/models/partialTemplate/update-partial-template.dto.ts
  src/models/subject/create-subject.dto.ts
  src/models/subject/update-subject.dto.ts
  src/models/template/create-template.dto.ts
  src/models/template/update-template.dto.ts
  src/partial-templates/partial-templates.controller.spec.ts
  src/partial-templates/partial-templates.controller.ts
  src/partial-templates/partial-templates.service.ts
  src/prisma.service.ts
  src/subject/subject.controller.spec.ts
  src/subject/subject.controller.ts
  src/subject/subject.module.ts
  src/subject/subject.service.spec.ts
  src/subject/subject.service.ts
  src/templates/templates.service.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#36 Update general auth logic
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/decorators/public.decorator.ts
  src/auth/strategies/guards/jwt-auth.guard.ts
  src/auth/strategies/guards/local-auth.guard.ts
  src/auth/strategies/jwt.strategy.ts
  src/auth/strategies/local.strategy.ts
  src/educational-programs/educational-programs.controller.ts
  src/partial-templates/partial-templates.controller.ts
  src/users/users.controller.ts
Labels: upgrade

#32 Fixed missing imports
  src/partial-templates/partial-templates.controller.ts
Labels: minor bug

#38 Proyect dockerized
  .dockerignore
  .gitignore
  Dockerfile
  README.Docker.md
  compose.yaml
  src/partial-templates/partial-templates.controller.ts
Labels: upgrade

#40 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: upgrade

#41 Implementations of prisma error handler
  src/app.module.ts
  src/areas/areas.service.ts
  src/common/validation/prisma-error-handler.ts
  src/educational-programs/educational-programs.service.ts
  src/partial-templates/partial-templates.service.ts
  src/subject/subject.service.ts
  src/templates/templates.service.ts
Labels: upgrade
